"""
Command Categories Package

Contains all command category implementations.
"""

from .administrator import (
    alert,
    alertuser,
    restrict,
    shutdown,
    switchserv,
    unrestrict,
    user,
)
from .clan import clan_create, clan_disband, clan_help, clan_info, clan_leave, clan_list
from .developer import (
    addpriv,
    debug,
    debug_focus,
    givedonator,
    py,
    recalc,
    reload,
    rmpriv,
    server,
    stealth,
    wipemap,
)
from .mappool import (
    pool_add,
    pool_create,
    pool_delete,
    pool_help,
    pool_info,
    pool_list,
    pool_remove,
)
from .moderator import addnote, notes, silence, unsilence
from .multiplayer import (
    mp_abort,
    mp_addref,
    mp_condition,
    mp_endscrim,
    mp_force,
    mp_freemods,
    mp_help,
    mp_host,
    mp_invite,
    mp_listref,
    mp_loadpool,
    mp_lock,
    mp_map,
    mp_mods,
    mp_randpw,
    mp_rematch,
    mp_rmref,
    mp_scrim,
    mp_start,
    mp_teams,
    mp_unloadpool,
    mp_unlock,
)
from .nominator import _map, request, requests
from .season import (
    recalc_season_stats,
    season_create,
    season_end,
    season_list,
    season_schedule,
    season_start,
    seasons,
    seasons_all,
)
from .user import (
    _with,
    apikey,
    block,
    changename,
    maplink,
    recent,
    reconnect,
    roll,
    top,
    unblock,
)

__all__ = [
    # User commands
    "roll",
    "recent",
    "top",
    "block",
    "unblock",
    "reconnect",
    "changename",
    "maplink",
    "apikey",
    "_with",
    # Nominator commands
    "request",
    "requests",
    "_map",
    # Moderator commands
    "silence",
    "unsilence",
    "notes",
    "addnote",
    # Administrator commands
    "user",
    "restrict",
    "unrestrict",
    "alert",
    "alertuser",
    "shutdown",
    "switchserv",
    # Developer commands
    "debug",
    "reload",
    "py",
    "addpriv",
    "debug_focus",
    "givedonator",
    "recalc",
    "rmpriv",
    "server",
    "stealth",
    "wipemap",
    # Multiplayer commands
    "mp_help",
    "mp_start",
    "mp_abort",
    "mp_map",
    "mp_mods",
    "mp_freemods",
    "mp_host",
    "mp_randpw",
    "mp_invite",
    "mp_addref",
    "mp_rmref",
    "mp_listref",
    "mp_lock",
    "mp_unlock",
    "mp_teams",
    "mp_condition",
    "mp_scrim",
    "mp_endscrim",
    "mp_rematch",
    "mp_force",
    "mp_loadpool",
    "mp_unloadpool",
    # Mappool commands
    "pool_help",
    "pool_create",
    "pool_delete",
    "pool_add",
    "pool_remove",
    "pool_list",
    "pool_info",
    # Clan commands
    "clan_help",
    "clan_create",
    "clan_disband",
    "clan_info",
    "clan_leave",
    "clan_list",
    # Season commands
    "season_create",
    "season_start",
    "season_end",
    "recalc_season_stats",
    "season_list",
    "season_schedule",
    "seasons",
    "seasons_all",
]
